version: '3.3'
services:
  # app-mercadito:
  #   image: app-mercadito:v1.0.1
  #   networks:
  #     - postgresql
  #   ports:
  #     - '8080:8080'
  #   environment:
      
  postgresql:
    #container_name: postgresql-servidor
    image: postgres:latest

    networks:
      - postgresql
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${BASE_DE_DATOS}
      - POSTGRES_USER=${USUARIO}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./_data:/var/lib/postgresql
    restart: always

networks:
  postgresql: