version: '3.3'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    networks:
      - mired
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${BASE_DE_DATOS}
      - POSTGRES_USER=${USUARIO}
      - PGDATA=/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgresql.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgresql.entrypoints=postgresql"
      - "traefik.tcp.routers.postgresql.service=postgresql"
      - "traefik.tcp.services.postgresql.loadbalancer.server.port=5432"
    volumes:
      - /postgres/_data:/var/lib/postgresql/data
    restart: always

networks:
  mired:
    external: true