services:
  reverse-proxy:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # command:
    #   - "--api.insecure=true"
    #   - "--providers.docker=true"
    #   - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "6379:6379"
      - "5432:5432"
    networks:
      - mired
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/config.yml:/etc/traefik/config.yml:ro
      - ./certs:/etc/certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"

networks:
  mired:
    external: true